apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-frontend
        image: ashwiniparaye/ecommerce-frontend:v1
        ports:
        - containerPort: 3000
      - name: ecommerce-backend
        image: ashwiniparaye/ecommerce-backend:v1
        ports:
        - containerPort: 5000
