apiVersion: v1
kind: Pod
metadata:
  name: ecommerce
spec:
  containers:
  - name: frontend
    image: ashwiniparaye/ecommerce-frontend:v1
    ports:
    - containerPort: 3000

  - name: backend
    image: ashwiniparaye/ecommerce-backend:v1
    ports:
    - containerPort: 5000
